# Türklingel Event mit Snapshot
alias: Türklingel Activity Feed
description: Speichert Türklingel-Events im Daily Activity Feed
trigger:
  - platform: state
    entity_id: binary_sensor.doorbell
    to: "on"
action:
  # Push Notification
  - service: notify.mobile_app_handy
    data:
      message: "Es wurde geklingelt"
      title: "Türklingel"
  
  # Snapshot speichern (optional)
  - service: camera.snapshot
    target:
      entity_id: camera.doorbell
    data:
      filename: /config/www/doorbell_latest.jpg
  
  # Event an Daily Activity Feed senden
  - service: rest_command.daily_activity_event
    data:
      type: "doorbell"
      title: "Türklingel"
      text: "Es wurde an der Haustür geklingelt"
      image: "/local/doorbell_latest.jpg"

mode: single