# Haustür geöffnet Event
alias: Haustür Activity Feed
description: Speichert Haustür-Events im Daily Activity Feed
trigger:
  - platform: state
    entity_id: binary_sensor.front_door
    to: "on"
action:
  # Push Notification
  - service: notify.mobile_app_handy
    data:
      message: "Die Haustür wurde geöffnet"
      title: "Haustür"
  
  # Event an Daily Activity Feed senden
  - service: rest_command.daily_activity_event
    data:
      type: "door"
      title: "Haustür"
      text: "Die Haustür wurde um {{ now().strftime('%H:%M') }} Uhr geöffnet"

mode: single